from urllib.parse import urlparse


def generate_removal_draft(url: str, name: str, email: str) -> str:
    """Generate a GDPR Art.17 / CCPA removal request letter."""
    try:
        domain = urlparse(url).netloc or url
    except Exception:
        domain = url

    return f"""Subject: Personal Data Removal Request — GDPR Article 17 / CCPA

To Whom It May Concern,

I am writing to formally request the removal of my personal data from your website in accordance with my rights under:
  • The General Data Protection Regulation (GDPR), Article 17 — Right to Erasure ("Right to be Forgotten")
  • The California Consumer Privacy Act (CCPA) — Right to Delete

Page containing my personal data:
  {url}

My details appearing on this page:
  Name:  {name}
  Email: {email}

I request that you:
  1. Remove all personal data associated with me from the above URL immediately.
  2. Remove any cached or indexed copies of this content.
  3. Confirm in writing once the removal is complete.
  4. Ensure this data is not republished in the future.

Under GDPR you are required to respond within 30 days of receipt of this request.
Under CCPA you are required to respond within 45 days.

If you require verification of my identity, please contact me at: {email}

If you are not the correct party to handle this request, please forward it to your Data Protection Officer or Privacy Team.

Thank you for your prompt attention.

Sincerely,
{name}
{email}

---
Note: This request was generated by a local privacy dashboard tool. No third party has access to this correspondence.
"""
